ko-time:
  # 是否开启koTime，默认开启，当为false时，关闭koTime
  enable: true
  pointcut: execution(public * org.example..*.*(..))
  # 是否开启控制输出，默认false
  log-enable: false
  # 语言（english/chinese）默认chinese
  language: chinese
  # 时间阈值，用于前端展示，大于阈值显示红色，小于阈值显示绿色，默认800
  threshold: 800.0
  # 前端页面调用接口的上下文环境，无法自动获取时可手动配置，一般情况切记不要配置   v2.0.1开始支持
  #context-path: http://localhost:80
  # 是否开启异常检测，默认为false,开启后会对方法内部抛出的异常进行统计 v2.0.0开始支持
  exception-enable: true
    # 是否开启异常检测，默认为false,开启后会对方法内部抛出的异常进行统计 v2.0.0开始支持
  auth-enable: true
  # 登录用户 v2.0.2开始支持
  user-name: admin
  # 登录密码 v2.0.2开始支持
  password: admin
  # 是否开启入参组合分析 默认开启 v2.0.8开始支持 双击方法节点即可看到效果
  param-analyse: true
  # 启动时是否删除过往数据 默认false v2.2.3开始支持
  data-reset: false
  # 调用信息存储线程数（为了不影响项目本身性能，链路存储异步进行），默认2，该值并非越大越好，瓶颈取决于数据库性能和服务器配置，尽可能少占用项目资源为上  v2.2.0-BETA开始支持
  thread-num: 2
  # 丢弃率（0-1） 同一个方法在多次连续调用时，耗时差距并不大，为了存储的IO性能考虑，可以随机丢弃一部分耗时数据。默认30% v2.2.5开始支持
  discard-rate: 0.3
  # 登录超时时间考虑 默认43200s(12个小时) v2.3.0开始支持
  auth-expire: 43200

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kotime?useSSL=false&useUnicode=true&characterEncoding=UTF-8&AllowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.mysql: debug